# Generated by Django 3.0.2 on 2020-04-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200, null=True)),
                ('target_area', models.IntegerField(choices=[(1, 'Upper'), (2, 'Lower'), (3, 'General'), (4, 'Oblique')])),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Extreme')])),
            ],
        ),
    ]
